### PR TITLE
added disco.io

### PR DESCRIPTION
**Pull request by antoinem**
Hi,

I just added http://disco.io

Best,
Antoine

### CODE REVIEW

**Comment by iangilman** [comment]
Awesome, thank you! Is this your project? Looks very cool. Do you have any plans for an API? I would love to build on something like that. Also, why no Spotify? Is that in the works?

**Comment by iangilman** [comment]
Published: http://iangilman.com/rdio-exodus/

**Comment by antoinem** [comment]
Thanks to you!

Yes I’m building this with a friend.
We have many ideas, but as it’s very difficult to pay the bills with a music app, we don’t have a lot of time for this. An API could be nice for sure, but we are currently thinking about offering a way to discover music and browse other people playlists.

Re Spotify, they don’t make it very easy to do it. Their terms of service make it illegal to match a user content to other services (Your playlists belong to them…). Also their API doesn’t allow to stream full tracks (or we’d have to use their player, …). We might be able to do something illegally and not as nice as with Rdio or Deezer…
Another reason I’ll miss Rdio...

Best,

Antoine

**Comment by iangilman** [comment]
So I guess you wouldn't be able to import playlists from Spotify, but maybe it's no problem to export playlists to Spotify? And then people could play directly in Spotify (getting around the lack of playback API)? Anyway, probably best to focus on the nicer APIs for now. 

I look forward to seeing how your app develops!

**Pull request merged**
